targets:
  $default:
    builders:
      cloud_firestore_odm_generator:
        enabled: true
      json_serializable:
        options:
          create_field_map: true

builders:
  cloud_firestore_odm_generator:
    import: "package:cloud_firestore_odm_generator/cloud_firestore_odm_generator.dart"
    builder_factories: ["firebase"]
    build_extensions: { ".dart": [".firebase.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
    required_inputs: [".freezed.dart"]
