name: firebase_remote_config
description:
  Flutter plugin for Firebase Remote Config. Update your application look and feel and behavior without
  re-releasing.
homepage: https://firebase.google.com/docs/remote-config
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_remote_config/firebase_remote_config
version: 4.2.2

false_secrets:
  - example/**

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_core: ^2.13.1
  firebase_core_platform_interface: ^4.8.0
  firebase_remote_config_platform_interface: ^1.4.2
  firebase_remote_config_web: ^1.4.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  pedantic: ^1.8.0
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.firebaseremoteconfig
        pluginClass: FirebaseRemoteConfigPlugin
      ios:
        pluginClass: FLTFirebaseRemoteConfigPlugin
      macos:
        pluginClass: FLTFirebaseRemoteConfigPlugin
      web:
        default_package: firebase_remote_config_web
