name: firebase_in_app_messaging_example
description: Demonstrates how to use the firebase_in_app_messaging plugin.
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  firebase_analytics: ^10.4.2
  firebase_core: ^2.13.1
  firebase_in_app_messaging: ^0.7.3+2
  firebase_in_app_messaging_platform_interface: ^0.2.4+2
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
