# FlutterFire_X naming due to package being take already on Pub.dev.
name: firebase_app_installations
description: A Flutter plugin allowing you to use Firebase Installations.
version: 0.2.3+2
homepage: https://firebase.google.com/docs/projects/manage-installations#flutter
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_app_installations/firebase_app_installations

false_secrets:
  - example/**

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_app_installations_platform_interface: ^0.1.4+2
  firebase_app_installations_web: ^0.1.3+2
  firebase_core: ^2.13.1
  firebase_core_platform_interface: ^4.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.installations.firebase_app_installations
        pluginClass: FirebaseInstallationsPlugin
      ios:
        pluginClass: FirebaseInstallationsPlugin
      macos:
        pluginClass: FirebaseInstallationsPlugin
