name: firebase_analytics_example
description: Demonstrates how to use the firebase_analytics plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_analytics: ^10.4.2
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
