name: cloud_firestore_odm_example
version: 1.0.0-dev.1
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.0
  cloud_firestore_odm: ^1.0.0-dev.60
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.2
  cloud_firestore_odm_generator: ^1.0.0-dev.60
  cloud_firestore_odm_generator_integration_test:
    path: ../../cloud_firestore_odm_generator/cloud_firestore_odm_generator_integration_test
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  http: ^0.13.5
  integration_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mockito: ^5.0.0

flutter:
  uses-material-design: true
