name: firebase_auth
description: Flutter plugin for Firebase Auth, enabling Android and iOS
  authentication using passwords, phone numbers and identity providers
  like Google, Facebook and Twitter.
homepage: https://firebase.google.com/docs/auth
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth
version: 4.6.2

false_secrets:
  - example/**

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_auth_platform_interface: ^6.15.2
  firebase_auth_web: ^5.5.2
  firebase_core: ^2.13.1
  firebase_core_platform_interface: ^4.8.0
  flutter:
    sdk: flutter
  meta: ^1.8.0

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.auth
        pluginClass: FlutterFirebaseAuthPlugin
      ios:
        pluginClass: FLTFirebaseAuthPlugin
      macos:
        pluginClass: FLTFirebaseAuthPlugin
      web:
        default_package: firebase_auth_web
