name: firebase_messaging_example
description: Demonstrates how to use the firebase_messaging plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.0.0+1
  http: ^0.13.0

dependency_overrides:
  # Override for `flutter_local_notifications`:
  plugin_platform_interface: ^2.1.3

flutter:
  uses-material-design: true
