name: firebase_storage_web
description: The web implementation of firebase_storage
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_storage/firebase_storage_web
version: 3.6.2

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  _flutterfire_internals: ^1.3.2
  async: ^2.5.0
  firebase_core: ^2.13.1
  firebase_core_web: ^2.5.0
  firebase_storage_platform_interface: ^4.4.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^0.13.0
  js: ^0.6.3
  meta: ^1.8.0

dev_dependencies:
  firebase_core_platform_interface: ^4.8.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseStorageWeb
        fileName: firebase_storage_web.dart
