name: cloud_firestore_odm
description: An ODM for Firebase Cloud Firestore (cloud_firestore).
homepage: https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore_odm
repository: https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore_odm/cloud_firestore_odm
version: 1.0.0-dev.60

false_secrets:
  - example/**

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.0
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
