# Copyright 2021 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# in the LICENSE file.

include: ../../../../analysis_options.yaml
linter:
  rules:
    avoid_print: false
analyzer:
  errors:
    public_member_api_docs: ignore
