// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn6EmFSDFU1sPIOd_Cwo8JzQd6tk80Fz4',
    appId: '1:942964897023:web:27bd1054d9c2c695f808ca',
    messagingSenderId: '942964897023',
    projectId: 'dwasemana9',
    authDomain: 'dwasemana9.firebaseapp.com',
    storageBucket: 'dwasemana9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhrkhs3Zx57UdRM2ws6Z5C9kddhK_2lBg',
    appId: '1:942964897023:android:493757479326e6b1f808ca',
    messagingSenderId: '942964897023',
    projectId: 'dwasemana9',
    storageBucket: 'dwasemana9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ9C4n3uWmaSg9HFARSA9yRwk5Nf2zqKQ',
    appId: '1:942964897023:ios:0d4049ce73eaa501f808ca',
    messagingSenderId: '942964897023',
    projectId: 'dwasemana9',
    storageBucket: 'dwasemana9.appspot.com',
    iosClientId: '942964897023-g2p3tpt8p7ijpkr430bcev4qhv5gl4i2.apps.googleusercontent.com',
    iosBundleId: 'com.example.basedatos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ9C4n3uWmaSg9HFARSA9yRwk5Nf2zqKQ',
    appId: '1:942964897023:ios:0d4049ce73eaa501f808ca',
    messagingSenderId: '942964897023',
    projectId: 'dwasemana9',
    storageBucket: 'dwasemana9.appspot.com',
    iosClientId: '942964897023-g2p3tpt8p7ijpkr430bcev4qhv5gl4i2.apps.googleusercontent.com',
    iosBundleId: 'com.example.basedatos',
  );
}
