name: firebase_firestore_odm

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - 'packages/cloud_firestore/**'
      - 'packages/cloud_firestore_odm/**'
      - '.github/workflows/firebase_firestore_odm.yaml'
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'

env:
  FLUTTERFIRE_PLUGIN_SCOPE: '*cloud_firestore*'
  FLUTTERFIRE_PLUGIN_SCOPE_EXAMPLE: '*cloud_firestore_odm_example*'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@dd3c344d731938d2ab2567a261f54a19a68b5f6a
        with:
          run-bootstrap: false
          melos-version: '3.0.1'
      - name: 'Bootstrap Workspace'
        run: |
          melos bootstrap --scope="*firebase_core*" --scope="$FLUTTERFIRE_PLUGIN_SCOPE"
          melos run odm:example_build_runner:build
          melos run odm:generator_test_build_runner:build
      - name: 'Flutter Test'
        run: melos run odm:test:flutter --no-select
      - name: 'Dart Test'
        run: melos run odm:test:dart --no-select

  integration_test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        name: Install Node.js 16
        with:
          node-version: '16'
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d
        with:
          channel: 'stable'
          cache: true
      - uses: bluefireteam/melos-action@dd3c344d731938d2ab2567a261f54a19a68b5f6a
        with:
          run-bootstrap: false
          melos-version: '3.0.1'
      - name: 'Install Tools'
        run: |
          sudo npm i -g firebase-tools
      - name: 'Bootstrap Workspace'
        run: |
          melos bootstrap --scope="*firebase_core*" --scope="$FLUTTERFIRE_PLUGIN_SCOPE"
          melos run odm:example_build_runner:build
          melos run odm:generator_test_build_runner:build
      - name: Start Firebase Emulator
        run: cd ./.github/workflows/scripts && ./start-firebase-emulator.sh
      - name: 'E2E Tests'
        working-directory: packages/cloud_firestore_odm/cloud_firestore_odm/example
        # Web devices are not supported for the `flutter test` command yet. As a
        # workaround we can use the `flutter drive` command. Tracking issue:
        # https://github.com/flutter/flutter/issues/66264
        run: |
          chromedriver --port=4444 &
          flutter drive \
            --verbose-system-logs \
            -d web-server \
            --driver=test_driver/integration_test.dart \
            --target=integration_test/cloud_firestore_odm_e2e_test.dart \
            --dart-define=CI=true
