name: firebase_dynamic_links
description:
  Flutter plugin for Google Dynamic Links for Firebase, an app solution for creating
  and handling links across multiple platforms.
version: 5.3.2
homepage: https://firebase.google.com/docs/dynamic-links
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_dynamic_links

false_secrets:
  - example/**

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_core: ^2.13.1
  firebase_core_platform_interface: ^4.8.0
  firebase_dynamic_links_platform_interface: ^0.2.6+2
  flutter:
    sdk: flutter
  meta: ^1.8.0
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.dynamiclinks
        pluginClass: FlutterFirebaseDynamicLinksPlugin
      ios:
        pluginClass: FLTFirebaseDynamicLinksPlugin
