name: firebase_dynamic_links_example
description: Demonstrates how to use the firebase_dynamic_links plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_core: ^2.13.1
  firebase_dynamic_links: ^5.3.2
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10

flutter:
  uses-material-design: true
