name: firebase_ml_model_downloader_example
description: Demonstrates how to use the firebase_ml_model_downloader plugin.

publish_to: 'none'

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_ml_model_downloader: ^0.2.3+2

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
